config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :stocks, only: [:index] do
    collection do
      post :import
      post :rust_import
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stocks_controller.rb
require 'csv'
class StocksController < ApplicationController
  def index
  end

  def import
    file = params[:file]
    t0 = Time.now
    data = Hash.new { |h, k| h[k] = [] }
    CSV.foreach(file.path, headers: true) do |row|
      symbol = row.to_hash["symbol"]
      data[symbol] << row.to_hash
    end

    data.keys.each do |symbol|
      data[symbol] = data[symbol].sort do |a,b|
        b["close"].to_f <=> a["close"].to_f
      end
    end

    t1 = Time.now
    ellapsed_time = ((t1 - t0) * 1000.0).round(4)
    render json: {time: ellapsed_time, data: data.keys.reduce({}){ |memo, k| memo[k] = data[k][0...10]; memo }}
  end

  def rust_import
    file = params[:file]
    t0 = Time.now
    result = TopStocks.import(file.path)
    t1 = Time.now
    ellapsed_time = ((t1 - t0) * 1000.0).round(4)
    render json: {time: ellapsed_time, data: JSON.parse(result) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsvParser</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stocks/index.html.erb
<h1>Hello</h1>
<%= form_tag import_stocks_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag  "Import CSV (Slow)" %>
<% end %>
<hr>
<br>
<%= form_tag rust_import_stocks_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag  "Import CSV (Fast)" %>
<% end %>